version: "3.8"

services:

  backend:
    build: ./backend
    container_name: foodies-backend
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: foodies-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
